# Generated by Django 6.0.4 on 2026-04-12 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_user_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('x_subscription_status', models.JSONField(blank=True, default=dict)),
                ('x_subscription_last_checked', models.DateTimeField(blank=True, null=True)),
                ('is_x_subscriber', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
