# Generated by Django 6.0.4 on 2026-04-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorXCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default creator credential', max_length=80)),
                ('bearer_token', models.TextField(help_text='Creator account bearer token for X API lookups.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Creator X credential',
                'verbose_name_plural': 'Creator X credentials',
            },
        ),
    ]
