# Generated by Django 6.0.4 on 2026-04-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_subscriptions', '0002_creatorxcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='x_subscription_check_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='x_subscription_last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
